name: Export Snowflake DDLs

on:
  workflow_dispatch: # Trigger manually
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (adjust as needed)

jobs:
  export-ddls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Snowflake connector and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Export DDLs from Snowflake
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USER: ${{ secrets.SF_USER }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        run: |
          python ./export_ddls.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add snowflake_ddls/
          git commit -m "Export Snowflake DDLs"
          git push
