name: Snowflake DDL Extraction

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  extract-snowflake-ddls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-connector-python
    
    - name: Extract Snowflake DDLs
      env:
        SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_ROLE: ${{ secrets.SF_ROLE }}
        SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SF_DATABASE: ${{ secrets.SF_DATABASE }}  # Added database parameter
      run: |
        cat << 'EOF' > extract_ddls.py
        import snowflake.connector
        import os
        import json

        # Snowflake connection
        conn = snowflake.connector.connect(
            account=os.environ['SF_ACCOUNT'],
            user=os.environ['SF_USERNAME'],
            password=os.environ['SF_PASSWORD'],
            role=os.environ['SF_ROLE'],
            warehouse=os.environ['SF_WAREHOUSE'],
            database=os.environ['SF_DATABASE']  # Added database parameter
        )

        cursor = conn.cursor()

        # Function to create directory and save DDL
        def save_ddl(object_type, schema, name, ddl):
            # Create directory structure
            dir_path = f'snowflake_ddls/{object_type}/{schema}'
            os.makedirs(dir_path, exist_ok=True)
            
            # Save DDL to file
            file_path = f'{dir_path}/{name}.sql'
            with open(file_path, 'w') as f:
                f.write(ddl)

        # Get current database
        current_db = os.environ['SF_DATABASE']

        # Extract schemas
        cursor.execute(f"SHOW SCHEMAS IN DATABASE {current_db}")
        schemas = [row[1] for row in cursor.fetchall() if not row[1].startswith('INFORMATION_SCHEMA')]

        for schema in schemas:
            print(f"Processing schema: {schema}")
            
            try:
                # Tables
                cursor.execute(f"SHOW TABLES IN SCHEMA {current_db}.{schema}")
                for table in cursor.fetchall():
                    table_name = table[1]
                    print(f"Extracting DDL for table: {table_name}")
                    cursor.execute(f"SELECT GET_DDL('TABLE', '{current_db}.{schema}.{table_name}')")
                    ddl = cursor.fetchone()[0]
                    save_ddl('tables', schema, table_name, ddl)
                
                # Views
                cursor.execute(f"SHOW VIEWS IN SCHEMA {current_db}.{schema}")
                for view in cursor.fetchall():
                    view_name = view[1]
                    print(f"Extracting DDL for view: {view_name}")
                    cursor.execute(f"SELECT GET_DDL('VIEW', '{current_db}.{schema}.{view_name}')")
                    ddl = cursor.fetchone()[0]
                    save_ddl('views', schema, view_name, ddl)
                
                # Stored Procedures
                cursor.execute(f"SHOW PROCEDURES IN SCHEMA {current_db}.{schema}")
                for proc in cursor.fetchall():
                    proc_name = proc[1]
                    print(f"Extracting DDL for procedure: {proc_name}")
                    cursor.execute(f"SELECT GET_DDL('PROCEDURE', '{current_db}.{schema}.{proc_name}')")
                    ddl = cursor.fetchone()[0]
                    save_ddl('procedures', schema, proc_name, ddl)
            
            except Exception as e:
                print(f"Error processing schema {schema}: {str(e)}")
                continue

        conn.close()
        EOF
        python extract_ddls.py
    
    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add snowflake_ddls
        git commit -m "Update Snowflake DDLs" || exit 0
        git push
