name: Extract Snowflake DDLs

on:
  workflow_dispatch:  # Manual trigger
  schedule:           # Optional: scheduled runs
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  extract-ddls:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SnowSQL (to execute Snowflake queries)
    - name: Install SnowSQL
      run: |
        curl -O https://s3.amazonaws.com/snowflake-devops/snowflake-tools/snowcli/snowcli-latest.tar.gz
        tar -xvzf snowcli-latest.tar.gz
        sudo mv snowcli /usr/local/bin

    # Step 3: Run the SnowSQL command to extract DDLs
    - name: Extract DDLs from Snowflake
      env:
        SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
      run: |
        snowsql -a $SF_ACCOUNT -u $SF_USERNAME -p $SF_PASSWORD -o output_file=ddls/ddl_output.sql -q "
        SELECT GET_DDL('DATABASE', 'YOUR_DATABASE_NAME');
        "

    # Step 4: Commit and push DDLs back to the repository
    - name: Commit and push DDLs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ddls/
        git commit -m "Update Snowflake DDLs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
