name: Extract Snowflake DDLs

on:
  workflow_dispatch:

jobs:
  extract-ddls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Install SnowSQL CLI
        run: |
          curl -o snowsql.deb https://repo.snowflake.com/snowsql/ubuntu/snowflake-snowsql-latest_amd64.deb
          sudo dpkg -i snowsql.deb
          sudo apt-get install -f  # Ensure dependencies are installed

      - name: Set DNS for GitHub Actions runner
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf

      - name: Run Snowflake DDL extraction
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        run: |
          # Ensure SnowSQL is installed correctly
          snowsql --version

          # Query Snowflake to extract DDLs for all tables
          echo "Extracting DDLs from Snowflake..."
          snowsql -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -p $SF_PASSWORD \
            -q "SHOW TABLES IN SCHEMA PUBLIC;" | jq -r '.[].name' | while read table_name; do
              # For each table, extract the DDL
              echo "Extracting DDL for table: $table_name"
              snowsql -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -p $SF_PASSWORD \
                -q "SHOW CREATE TABLE $table_name;" > "$table_name-ddl.sql"
            done

      - name: Upload DDLs to artifact
        uses: actions/upload-artifact@v3
        with:
          name: ddl-files
          path: "*.sql"
