name: Extract Snowflake DDLs

on:
  workflow_dispatch:  # Manual trigger
  schedule:           # Optional: scheduled runs
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  extract-ddls:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python (if using a Python script)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies (if using a Python script)
    - name: Install dependencies
      run: pip install snowflake-connector-python

    # Step 4: Run the extraction script or SnowSQL commands
    - name: Extract DDLs
      env:
        SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
      run: |
        # Example: Using a Python script
        python extract_ddls.py

        # OR Example: Using SnowSQL
        snowsql -a $SF_ACCOUNT -u $SF_USERNAME -p $SF_PASSWORD -o output_file=ddls/ddl_output.sql -q "
        SELECT GET_DDL('DATABASE', 'YOUR_DATABASE_NAME');
        "

    # Step 5: Save DDLs back to the repository
    - name: Commit and push DDLs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ddls/
        git commit -m "Update Snowflake DDLs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
